# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: npm install
        
      - name: Run the tests
        run: npm test
        
      - name: Build
        run: npm run build
        
      - name: Deploy React app to server
        run: |
          scp -i ${{ secrets.SSH_KEY }} -r /home/runner/work/test-demo/test-demo/build/* root@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_DIR }}

#       - name: Copying files to server
#         uses: appleboy/scp-action@master
#         with:
#           host: ${{ secrets.REMOTE_HOST }}
#           username: ${{ secrets.REMOTE_USER }}
#           key: ${{ secrets.SSH_KEY }}
#           rm: true
#           source: "build/*"
#           target: ${{ secrets.REMOTE_DIR }}
